### ISSUE TITLE
脚注がポップアップしない？

### ISSUE THREAD

**Issue by okkez** [clear-code/tdiary-style-markdown#1]
脚注がポップアップしていないような気がする。
ツールチップ表示？

**Comment by okkez** [comment]
以前はこんな感じだった。

``` html
<a href="#fn1" title="脚注の内容">*1</a>
```

**Comment by okkez** [comment]
http://docs.tdiary.org/ja/?footnote.rb を使えばポップアップするようになる。
両方を混ぜて使うと、脚注の番号の同じものができたりする。

**Comment by okkez** [comment]
インラインスタイルのみの脚注を使うように統一してもよければ、Redcarpetのフックでfootnote.rbに置き換えるようにすることはできる。
脚注の位置が離れるスタイルの方は、Redcarpetがストリームで処理している都合上、脚注の内容を先に取得することができないため、脚注の内容をポップアップさせられない。

``` text
文章をかく[^こんな感じの脚注]
```

みたいになる。

pandoc_markdown だとインラインスタイルは以下のようになる。

``` text
文章をかく^[こんな感じの脚注]
```

**Comment by okkez** [comment]
コールバックでマーカーを埋め込んで、最後にfootnote.rbに置換するようにすれば、全てうまくいくはず。
あと、画像へのリンクも自動でtdiaryのプラグインに置き換えるとよさそう。

**Comment by kou** [comment]
tdiary-style-gfmと`fn`の組合せがあればtdiary-style-markdownは不要だったりしません？

**Comment by okkez** [comment]
不要かな、とも思ったのですが、tdiary-style-markdown の方がククログ独自のカスタマイズはしやすいかなぁ、と思っています。

**Comment by kou** [comment]
ククログ独自のカスタマイズって必要なんでしたっけ。

**Comment by okkez** [comment]
「今」必要なのか、という問いであれば独自カスタマイズは不要ですね。
結局、tdiary プラグインの存在を忘れてた(意識してなかった)のがtdiary-style-markdownを作った理由なので、このライブラリ自体不要ですね。

**Comment by okkez** [comment]
一応、脚注の自動変換は実装したのでRD形式のとき自分で使っていた範囲の機能についてはこのライブラリで実現できています。
